version: "3.6"

services:
  front-service:
    image: ${ECR_URL}/${ECR_URL}:${BUILD_NUMBER}
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - "80:3000"
